insert into nsoa(n_id,n_name,n_date) values(nsoa_s.nextval,'ÖÐÎç',sysdate);
select * from nsoa;



CREATE OR REPLACE PACKAGE NSOA_PKG is
  PROCEDURE NSOA_INSERT(P_NID IN NUMBER,P_NNAME IN VARCHAR2,P_NDATE IN DATE);
END NSOA_PKG;
/
CREATE OR REPLACE PACKAGE BODY NSOA_PKG is
  PROCEDURE NSOA_INSERT(P_NID IN NUMBER,P_NNAME IN VARCHAR2,P_NDATE IN DATE) IS 
  BEGIN
    NULL;
  END;
END NSOA_PKG;